-- Scene Table
create table if not exists public.scenes (
  id             bigint generated by default as identity primary key,
  project_id     bigint not null references public.projects(id) on delete cascade,
  user_id        bigint not null references public.users(id) on delete cascade, -- 단순 조회용
  status         varchar(15) not null default 'init', -- init > prompt > prompt_confirmed > image > image_confirmed > clip
  scene_id       varchar(20) not null,
  scene_json     json not null default '{}'::json,
  image_version  int4,
  clip_version   int4,
  "order"        int not null,           -- 예약어 회피, 반드시 쿼리 시 쌍따옴표 사용
  no_subject     boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- 인덱스
create index if not exists idx_scenes_project_id
  on public.scenes(project_id);

create index if not exists idx_scenes_scene_id
  on public.scenes(scene_id);

-- updated_at 트리거
drop trigger if exists trg_scenes_updated_at on public.scenes;
create trigger trg_scenes_updated_at
before update on public.scenes
for each row execute function public.set_updated_at();