-- Users Table
create table if not exists public.users (
  id            bigint generated by default as identity primary key,
  login_method  varchar(10) not null, -- password, google, kakao, ...
  email         text not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- updated_at 트리거
drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();