-- Project Table
create table if not exists public.projects (
  id                 bigint generated by default as identity primary key,
  user_id            bigint not null references public.users(id) on delete cascade,
  title              varchar(10) not null,
  description        varchar(200),
  script             varchar(2000),
  narration_version  int4,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

-- 인덱스
create index if not exists idx_projects_user_id
  on public.projects(user_id);

-- updated_at 트리거
drop trigger if exists trg_projects_updated_at on public.projects;
create trigger trg_projects_updated_at
before update on public.projects
for each row execute function public.set_updated_at();