-- Asset Table
create table if not exists public.assets (
  id           bigint generated by default as identity primary key,
  parents_id   varchar(30) not null,           -- 규칙: narration-{project_id} / image-{scene_id} / clip-{scene_id}
  version      int4 not null default 1,
  user_id      bigint not null references public.users(id) on delete cascade, -- 단순 조회용
  type         varchar(10) not null,           -- narration | clip | image
  storage_url  varchar(300) not null,
  metadata     json not null default '{}'::json,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- 조회 최적화(복합 인덱스)
create index if not exists idx_assets_parents_type_version
  on public.assets(parents_id, type, version);

-- (유니크 제약으로 버전 중복 방지)
create unique index if not exists uq_assets_parents_type_version
  on public.assets(parents_id, type, version);

-- updated_at 트리거
drop trigger if exists trg_assets_updated_at on public.assets;
create trigger trg_assets_updated_at
before update on public.assets
for each row execute function public.set_updated_at();