-- Video Preference Table (projects 테이블 1:1 대응)
create table if not exists public.video_preferences (
  id               bigint generated by default as identity primary key,
  project_id       bigint not null references public.projects(id) on delete cascade,
  image_gen_model  varchar(50) not null default 'Gemini',   -- Gemini, GPT
  video_gen_model  varchar(50) not null default 'Seedance', -- Kling, Seedance
  voice_gen_model  varchar(50) not null default 'Bin',      -- Bin, Otani
  stability        double precision not null default 0.5,
  resolution       varchar(10) not null default '480p',     -- 480p, 720p, ...
  custom_style     varchar(200),
  split_rule       varchar(1200),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- 프로젝트당 1행 보장(유니크)
create unique index if not exists idx_video_prefs_project_unique
  on public.video_preferences(project_id);

-- (요청 명시 인덱스)
create index if not exists idx_video_prefs_project_id
  on public.video_preferences(project_id);

-- updated_at 트리거
drop trigger if exists trg_video_prefs_updated_at on public.video_preferences;
create trigger trg_video_prefs_updated_at
before update on public.video_preferences
for each row execute function public.set_updated_at();