-- Token Table
create table if not exists public.tokens (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references public.users(id) on delete cascade,
  type       varchar(10) not null,  -- gpt, gemini, seedance
  usage      int4 not null default 0,
  "limit"    int4 not null,         -- 예약어 충돌 방지
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 인덱스 & 유니크 바인딩
create unique index if not exists idx_tokens_user_type_unique
  on public.tokens(user_id, type);

-- updated_at 트리거
drop trigger if exists trg_tokens_updated_at on public.tokens;
create trigger trg_tokens_updated_at
before update on public.tokens
for each row execute function public.set_updated_at();